---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by davide.gozzi.
--- DateTime: 9/30/2022 11:18 AM
---
function IsProficient (skill)
    if not character.Stash.ContainsKey(skill) then
        return false
    end
    return character.Stash[skill]
end


function Calculate()
    return
    {
        Acrobatics = GetModificator(character.Stats.Dexterity) + (IsProficient("Acrobatics") and character.ProficiencyModificator or 0),
        Athletics = GetModificator(character.Stats.Strength) + (IsProficient("Athletics") and character.ProficiencyModificator or 0),
        IsProficient = function(skill, isProficient)
            character.Stash[skill] = function(nothing)
                return isProficient
            end
        end
    }
end